name: Test standard

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
    test-ruleset:
        name: Test rules on PHP ${{ matrix.php-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
        steps:
            - uses: actions/checkout@v3
            - name: Install xmllint
              run: |
                sudo apt update
                sudo apt install --no-install-recommends -y libxml2-utils
                sudo apt clean
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
            - name: Cache module
              uses: actions/cache@v3
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install
            - name: Lint the ruleset
              run: xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd Wdes/ruleset.xml
            - name: Lint the test coding standard file
              run: xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd tests/phpcs.xml
            - name: Test the ruleset
              run: ./vendor/bin/phpcs --standard=Wdes -vv | grep -oF "Processing ruleset $(pwd)/Wdes/ruleset.xml"
            - name: Test some rules
              # Remove last lines to not assert on the time that was necessary to process the files
              run: ./vendor/bin/phpcs --standard=tests/phpcs.xml tests/ | sed '$d' | sed '$d' > process.out
            - name: Test that there is no diff
              run: diff -s tests/phpcs.out process.out
